use_frameworks!

target 'DSLoadable_Example' do
  pod 'DSLoadable', :path => '../'
  
  pod 'MSAutoView'
  pod 'NVActivityIndicatorView'

  target 'DSLoadable_Tests' do
    inherit! :search_paths

    
  end
end
